### ISSUE TITLE
Unable to install from straight

### ISSUE THREAD

**Issue by dissonauro-hex** [delehef/org-project#1]
Hi, i was trying to install the package with the following code but didn't work:
```
(use-package org-project
  :straight (org-project :type git :host github :repo "delehef/org-project")
  :bind (:map project-prefix-map
              ("t" . org-project-quick-capture)
              ("T" . org-project-capture)
              ("o" . org-project-open-todos))
  :custom
  (org-project-todos-per-project t))
```

I receved the following error:
`org-project--completing-read: Wrong type argument: stringp, (Git "~/.emacs.d/straight/repos/org-project/")`

I had to changed the org-project--current-project function and it worked but i know nearly nothing about Lisp, not sure if its ok to do this:

```
(defun org-project--current-project ()
  "Return the root of the current project if any, errors otherwise."
  (let ((project (project-root (project-current t))))
    (if project
        project
      (error "%s is not in a project" (buffer-name)))))
```

**Comment by delehef** [comment]
Would you mind giving your emacs version, and the result of `M-:`, `(project-current)` in the incriminated project?

**Comment by dissonauro-hex** [comment]
I'm using `GNU Emacs 28.1` when i evaluate `(current-project)` it returns `(vc Git "~/Projects/exercism/javascript/")`

**Comment by delehef** [comment]
Would you mind updating to the newest version and seeing whether it works out-of-the-box now?

**Comment by dissonauro-hex** [comment]
I just updated the package and everything is working now!

Thanks!

**Comment by delehef** [comment]
My pleasure, thanks for the bug report!
